# Generated by Django 5.2.1 on 2025-08-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userprofile_uuid'),
        ('project_profiling', '0002_projectprofile_assigned_to_projectprofile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprofile',
            name='budget',
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='approved_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='city_province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='client_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='client_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='client_contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='contract_agreement',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='gc_company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='gc_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='gc_contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='gc_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='gc_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='permits_licenses',
            field=models.FileField(blank=True, null=True, upload_to='permits/'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='subcontractors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='project_manager',
            field=models.ForeignKey(limit_choices_to={'role': 'Project Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to='authentication.userprofile'),
        ),
    ]
