# Generated by Django 5.2.1 on 2025-08-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userprofile_uuid'),
        ('project_profiling', '0003_remove_projectprofile_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprofile',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='project_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Project Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='projectprofile',
            name='status',
            field=models.CharField(choices=[('PL', 'Planned'), ('OG', 'Ongoing'), ('CP', 'Completed'), ('CN', 'Cancelled')], default='PL', max_length=20),
        ),
    ]
