# Generated by Django 5.2.1 on 2025-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0006_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overall project progress (%)', max_digits=5),
        ),
    ]
