# Generated by Django 5.2.1 on 2025-08-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0008_projectcost_projectreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LAB', 'Labor'), ('MAT', 'Materials'), ('EQP', 'Equipment'), ('SUB', 'Subcontractor'), ('OTH', 'Other')], max_length=3)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='project_profiling.projectprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectReport',
        ),
    ]
