# Generated by Django 5.2.1 on 2025-08-26 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0009_projectbudget_delete_projectreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprofile',
            name='allocated_funds',
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_allocated', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('project_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='project_profiling.projectbudget')),
            ],
            options={
                'ordering': ['-date_allocated'],
            },
        ),
    ]
