# Generated by Django 5.2.1 on 2025-08-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userprofile_uuid'),
        ('project_profiling', '0010_remove_projectprofile_allocated_funds_fundallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='budget_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='budget_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_reviews', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='budget_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
