# Generated by Django 5.2.1 on 2025-08-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0011_projectprofile_budget_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprofile',
            name='budget_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='projectprofile',
            name='budget_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='projectprofile',
            name='budget_status',
        ),
    ]
