# Generated by Django 5.2.1 on 2025-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_rename_progress_projecttask_weight_progressupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current approved progress % for this task', max_digits=5),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight contribution to project (%)', max_digits=5),
        ),
    ]
