# Generated by Django 5.2.1 on 2025-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_projecttask_progress_alter_projecttask_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
