# Generated by Django 5.2.1 on 2025-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_projecttask_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('PL', 'Planned'), ('OG', 'Ongoing'), ('CP', 'Completed')], default='PL', max_length=2),
        ),
    ]
