# Generated by Django 5.2.1 on 2025-08-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0008_projectcost_projectreport'),
        ('scheduling', '0007_projecttask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_profiling.projectcost')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.projecttask')),
            ],
        ),
    ]
