# Generated by Django 5.2.1 on 2025-08-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0009_projectbudget_delete_projectreport'),
        ('scheduling', '0008_taskcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcost',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_costs', to='project_profiling.projectcost'),
        ),
        migrations.AlterField(
            model_name='taskcost',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_costs', to='scheduling.projecttask'),
        ),
    ]
