# Generated by Django 5.2.1 on 2025-08-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_profiling', '0005_alter_projectprofile_project_manager'),
        ('scheduling', '0002_projecttask_duration_days_projecttask_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='location',
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(blank=True, max_length=50, null=True)),
                ('accomplished_to_date', models.CharField(blank=True, max_length=50, null=True)),
                ('accomplished_before', models.CharField(blank=True, max_length=50, null=True)),
                ('accomplished_this_period', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='project_profiling.projectprofile')),
            ],
        ),
    ]
