# Generated by Django 5.2.1 on 2025-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('VO', 'View Only'), ('SA', 'Super Admin'), ('PM', 'Project Manager'), ('OM', 'Operations Manager'), ('EG', 'Engineer')], default='VO', max_length=2),
        ),
    ]
