# Generated by Django 5.2.1 on 2025-08-16 17:11
from django.db import migrations
import uuid

def fix_duplicate_uuids(apps, schema_editor):
    UserProfile = apps.get_model("authentication", "UserProfile")
    seen = set()
    for profile in UserProfile.objects.all():
        if profile.uuid in seen or profile.uuid is None:
            profile.uuid = uuid.uuid4()
            profile.save(update_fields=["uuid"])
        seen.add(profile.uuid)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_uuids),
    ]
