# Generated by Django 5.2.1 on 2025-08-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_source', models.CharField(choices=[('GC', 'General Contractor'), ('DC', 'Direct Client')], max_length=20)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commercial'), ('IND', 'Industrial'), ('OTH', 'Other')], max_length=10)),
                ('project_category', models.CharField(blank=True, choices=[('PUB', 'Public'), ('PRI', 'Private'), ('REN', 'Renovation'), ('NEW', 'New Build')], max_length=10, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=300)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=200, null=True)),
                ('site_engineer', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('OG', 'Ongoing'), ('CP', 'Completed'), ('CN', 'Cancelled')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
