# Generated by Django 5.2.1 on 2025-08-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userprofile_uuid'),
        ('project_profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprofile',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='projectprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to='authentication.userprofile'),
        ),
    ]
