# Generated by Django 5.2.1 on 2025-08-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userprofile_uuid'),
        ('project_profiling', '0004_alter_projectprofile_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprofile',
            name='project_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile'),
        ),
    ]
