# Generated by Django 5.2.1 on 2025-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SA', 'Super Admin'), ('PM', 'Project Manager'), ('OM', 'Operations Manager'), ('EG', 'Engineer')], max_length=2),
        ),
    ]
