# Generated by Django 5.2.1 on 2025-08-16 17:07

from django.db import migrations,models
import uuid

def generate_unique_uuids(apps, schema_editor):
    UserProfile = apps.get_model("authentication", "UserProfile")
    for profile in UserProfile.objects.all():
        if not profile.uuid:  # only set if empty
            profile.uuid = uuid.uuid4()
            profile.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userprofile_token_version_userprofile_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.RunPython(generate_unique_uuids),
        migrations.AlterField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]